import { GameCtxProvider } from "@/contexts/GameCtx";
import { TriviaCtxProvider } from "@/contexts/TriviaCtx";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GameCtxProvider>
          <TriviaCtxProvider>{children}</TriviaCtxProvider>
        </GameCtxProvider>
      </body>
    </html>
  );
}
